// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// km_core
NumericVector km_core(const NumericVector& t_sorted, const NumericVector& e_sorted, double t_eval);
RcppExport SEXP _FastSurvival_km_core(SEXP t_sortedSEXP, SEXP e_sortedSEXP, SEXP t_evalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type t_sorted(t_sortedSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type e_sorted(e_sortedSEXP);
    Rcpp::traits::input_parameter< double >::type t_eval(t_evalSEXP);
    rcpp_result_gen = Rcpp::wrap(km_core(t_sorted, e_sorted, t_eval));
    return rcpp_result_gen;
END_RCPP
}
// logrank_core
NumericVector logrank_core(const NumericVector& time_sorted, const IntegerVector& event_sorted, const IntegerVector& j_sorted);
RcppExport SEXP _FastSurvival_logrank_core(SEXP time_sortedSEXP, SEXP event_sortedSEXP, SEXP j_sortedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type time_sorted(time_sortedSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type event_sorted(event_sortedSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j_sorted(j_sortedSEXP);
    rcpp_result_gen = Rcpp::wrap(logrank_core(time_sorted, event_sorted, j_sorted));
    return rcpp_result_gen;
END_RCPP
}
// pihe_core
NumericVector pihe_core(const NumericVector& time_sorted, const IntegerVector& event_sorted, const IntegerVector& j_sorted);
RcppExport SEXP _FastSurvival_pihe_core(SEXP time_sortedSEXP, SEXP event_sortedSEXP, SEXP j_sortedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type time_sorted(time_sortedSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type event_sorted(event_sortedSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j_sorted(j_sortedSEXP);
    rcpp_result_gen = Rcpp::wrap(pihe_core(time_sorted, event_sorted, j_sorted));
    return rcpp_result_gen;
END_RCPP
}
// rpiece_unif_cpp
NumericVector rpiece_unif_cpp(int n, const NumericVector& a_time, const NumericVector& cum_p);
RcppExport SEXP _FastSurvival_rpiece_unif_cpp(SEXP nSEXP, SEXP a_timeSEXP, SEXP cum_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type a_time(a_timeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cum_p(cum_pSEXP);
    rcpp_result_gen = Rcpp::wrap(rpiece_unif_cpp(n, a_time, cum_p));
    return rcpp_result_gen;
END_RCPP
}
// rpiece_exp_cpp
NumericVector rpiece_exp_cpp(int n, const NumericVector& hazard, const NumericVector& fin_time, const NumericVector& cum_haz);
RcppExport SEXP _FastSurvival_rpiece_exp_cpp(SEXP nSEXP, SEXP hazardSEXP, SEXP fin_timeSEXP, SEXP cum_hazSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type hazard(hazardSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type fin_time(fin_timeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cum_haz(cum_hazSEXP);
    rcpp_result_gen = Rcpp::wrap(rpiece_exp_cpp(n, hazard, fin_time, cum_haz));
    return rcpp_result_gen;
END_RCPP
}
// interleave_groups
DataFrame interleave_groups(const DataFrame& df_ctrl, const DataFrame& df_trt, int nsim, int n_ctrl, int n_trt);
RcppExport SEXP _FastSurvival_interleave_groups(SEXP df_ctrlSEXP, SEXP df_trtSEXP, SEXP nsimSEXP, SEXP n_ctrlSEXP, SEXP n_trtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type df_trt(df_trtSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< int >::type n_trt(n_trtSEXP);
    rcpp_result_gen = Rcpp::wrap(interleave_groups(df_ctrl, df_trt, nsim, n_ctrl, n_trt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastSurvival_km_core", (DL_FUNC) &_FastSurvival_km_core, 3},
    {"_FastSurvival_logrank_core", (DL_FUNC) &_FastSurvival_logrank_core, 3},
    {"_FastSurvival_pihe_core", (DL_FUNC) &_FastSurvival_pihe_core, 3},
    {"_FastSurvival_rpiece_unif_cpp", (DL_FUNC) &_FastSurvival_rpiece_unif_cpp, 3},
    {"_FastSurvival_rpiece_exp_cpp", (DL_FUNC) &_FastSurvival_rpiece_exp_cpp, 4},
    {"_FastSurvival_interleave_groups", (DL_FUNC) &_FastSurvival_interleave_groups, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastSurvival(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
