#' Create analysis datasets from clinical trial simulation data
#'
#' This function creates analysis datasets from simulation data generated by simTrial()
#' based on either target number of events or follow-up times for interim and final
#' analyses using data.table for maximum performance.
#'
#' @param data A data.table containing simulation data generated by simTrial().
#' @param E A numeric vector specifying the target number of events for each analysis.
#'   Cannot be used with followup. Default is NULL.
#' @param followup A numeric vector specifying the follow-up times for each analysis.
#'   Cannot be used with E. Default is NULL.
#'
#' @return A data.table containing the analysis datasets with the following columns:
#' \describe{
#'   \item{analysis}{Analysis number (1, 2, 3, ...)}
#'   \item{simID}{Simulation iteration ID (1 to nsim)}
#'   \item{group}{Group indicator (1, 2, 3, ...)}
#'   \item{subgroup}{Subgroup indicator (A, B, C, ...) - only present if subgroups are specified}
#'   \item{accrual.time}{Patient accrual time from study start}
#'   \item{surv.time}{Survival time from patient entry}
#'   \item{dropout.time}{Time to dropout from patient entry}
#'   \item{tte}{Time-to-event (adjusted for analysis cutoff)}
#'   \item{total}{Total time from study start}
#'   \item{dropout}{Original dropout indicator}
#'   \item{analysis.time}{Analysis cutoff time}
#'   \item{event}{Event indicator (1 = event occurred, 0 = censored)}
#' }
#'
#' @examples
#' library(data.table)
#'
#' # Generate simulation data
#' data <- simTrial(
#'   nsim = 100,
#'   N = list(
#'     group1 = c(A = 25, B = 112, C = 113),
#'     group2 = c(A = 25, B = 112, C = 113)
#'   ),
#'   a.time = list(
#'     group1 = list(A = c(0, 5, 10, 15, 20, 25), B = c(0, 5, 10, 15, 20, 25), C = c(0, 5, 10, 15, 20, 25)),
#'     group2 = list(A = c(0, 5, 10, 15, 20, 25), B = c(0, 5, 10, 15, 20, 25), C = c(0, 5, 10, 15, 20, 25))
#'   ),
#'   intensity = list(
#'     group1 = list(A = c(3.5, 14.3, 28.9, 43.6, 45), B = c(3.5, 14.3, 28.9, 43.6, 45) ,C = c(3.5, 14.3, 28.9, 43.6, 45)),
#'     group2 = list(A = c(3.5, 14.3, 28.9, 43.6, 45), B = c(3.5, 14.3, 28.9, 43.6, 45) ,C = c(3.5, 14.3, 28.9, 43.6, 45))
#'   ),
#'   e.time = list(
#'     group1 = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf)),
#'     group2 = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     group1 = list(A = log(2) / 5.811, B = log(2) / 5.811, C = log(2) / 5.811),
#'     group2 = list(A = log(2) / 4.3, B = log(2) / 4.3, C = log(2) / 4.3)
#'   ),
#'   d.time = list(
#'     group1 = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf)),
#'     group2 = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf))
#'   ),
#'   d.hazard = list(
#'     group1 = list(A = 0.01, B = 0.01, C = 0.01),
#'     group2 = list(A = 0.01, B = 0.01, C = 0.01)
#'   ),
#'   seed = 1
#' )
#'
#' # Analysis based on target number of events
#' analysis_events <- analysisData(data, E = c(142, 248, 354))
#'
#' # Analysis based on follow-up times
#' analysis_followup <- analysisData(data, followup = c(20, 25, 30))
#'
#' @import data.table
#' @export
analysisData <- function(data, E = NULL, followup = NULL) {

  # Input validation
  if (is.null(E) && is.null(followup)) {
    stop("Either E or followup must be specified")
  }

  if (!is.null(E) && !is.null(followup)) {
    stop("Cannot specify both E and followup arguments")
  }

  # Ensure data is a data.table
  if (!is.data.table(data)) {
    data <- as.data.table(data)
  }

  # Sort data by simulation ID and total time for efficient processing
  setorder(data, simID, total)

  if (!is.null(E)) {
    # Event-driven analysis
    n_analyses <- length(E)
    n_rows <- nrow(data)

    # Create expanded dataset efficiently using data.table operations
    expanded_data <- data[rep(seq_len(n_rows), n_analyses)]

    # Add analysis indicator
    expanded_data[, analysis := rep(seq_len(n_analyses), each = n_rows)]

    # Calculate analysis times and event indicators by group
    # First, identify event times (where dropout != 1) for each simulation
    expanded_data[, `:=`(
      row_id = seq_len(.N),
      is_event = as.integer(dropout != 1)
    ), by = .(analysis, simID)]

    # Calculate cumulative event count and find analysis time
    expanded_data[, event_rank := cumsum(is_event), by = .(analysis, simID)]

    # Find the analysis time (total time of the E[analysis]-th event)
    analysis_times <- expanded_data[
      is_event == 1,
      .(analysis.time = total[E[analysis[1]]]),
      by = .(analysis, simID)
    ]

    # Merge analysis times back to the main dataset
    expanded_data <- expanded_data[analysis_times, on = .(analysis, simID)]

    # Calculate adjusted time-to-event and event indicator
    expanded_data[, `:=`(
      tte = ifelse(total > analysis.time,
                   analysis.time - accrual.time,
                   tte),
      event = as.integer(total <= analysis.time & dropout != 1)
    )]

    # Clean up temporary columns and filter
    expanded_data[, `:=`(row_id = NULL, is_event = NULL, event_rank = NULL)]
    expanded_data <- expanded_data[tte >= 0]

  } else {
    # Time-driven analysis
    n_analyses <- length(followup)
    n_rows <- nrow(data)

    # Create expanded dataset efficiently using data.table operations
    expanded_data <- data[rep(seq_len(n_rows), n_analyses)]

    # Add analysis indicator and analysis time
    expanded_data[, `:=`(
      analysis = rep(seq_len(n_analyses), each = n_rows),
      analysis.time = rep(rep(followup, each = n_rows))
    )]

    # Calculate adjusted time-to-event and event indicator
    expanded_data[, `:=`(
      tte = ifelse(total > analysis.time,
                   analysis.time - accrual.time,
                   tte),
      event = as.integer(total <= analysis.time & dropout != 1)
    )]

    # Filter out negative time-to-event
    expanded_data <- expanded_data[tte >= 0]
  }

  # Set optimal column order
  if ("subgroup" %in% names(expanded_data)) {
    column_order <- c("analysis", "simID", "group", "subgroup", "accrual.time",
                      "surv.time", "dropout.time", "tte", "total", "dropout",
                      "analysis.time", "event")
  } else {
    column_order <- c("analysis", "simID", "group", "accrual.time", "surv.time",
                      "dropout.time", "tte", "total", "dropout", "analysis.time", "event")
  }

  setcolorder(expanded_data, column_order)

  return(expanded_data)
}
