#' Overall population statistical analysis summary for clinical trial data
#'
#' This function performs overall population statistical analysis on clinical trial data
#' generated by \code{\link{analysisData}}. It calculates log-rank test statistics,
#' p-values, hazard ratios, patient counts, event counts, and analysis times using
#' dplyr for maximum performance.
#'
#' @param data A tibble containing analysis data generated by \code{\link{analysisData}}.
#'   Must contain columns: simID, analysis, group, tte, event, analysis.time.
#' @param control A numeric value indicating which value in \code{group} represents
#'   the control group. Default is 1.
#' @param side A numeric value indicating the type of test: 1 for one-sided test,
#'   2 for two-sided test. Default is 2.
#' @param hr_est_method A character string specifying the hazard ratio estimation method.
#'   Must be one of "PY", "Pike", "Peto", "LR", or "Cox". Default is "Cox".
#'
#' @return A tibble containing overall population analysis results with the following columns:
#' \describe{
#'   \item{simID}{Simulation iteration ID}
#'   \item{analysis}{Analysis number}
#'   \item{subgroup}{Always "Overall" for overall population}
#'   \item{analysis_time}{Analysis cutoff time (calendar time from study start)}
#'   \item{lr_statistic}{Log-rank test statistic}
#'   \item{lr_pvalue}{Log-rank test p-value (one-sided or two-sided based on side parameter)}
#'   \item{hazard_ratio}{Estimated hazard ratio}
#'   \item{hr_method}{Method used for hazard ratio estimation}
#'   \item{n_total}{Total number of patients}
#'   \item{n_control}{Number of patients in control group}
#'   \item{n_treatment}{Number of patients in treatment group}
#'   \item{events_total}{Total number of events}
#'   \item{events_control}{Number of events in control group}
#'   \item{events_treatment}{Number of events in treatment group}
#' }
#'
#' @details
#' This function provides overall population summary of clinical trial results by:
#'
#' \describe{
#'   \item{Log-rank Test}{
#'     Performs log-rank test using \code{\link{lrtest}} for the overall population
#'     at each analysis timepoint. Returns test statistic and p-value based on the side parameter.
#'   }
#'   \item{Hazard Ratio Estimation}{
#'     Calculates hazard ratios using \code{\link{esthr}} for the overall population
#'     using the specified method.
#'   }
#'   \item{Patient and Event Counts}{
#'     Summarizes patient numbers and event numbers by group for the overall population.
#'   }
#'   \item{Analysis Time}{
#'     Records the analysis cutoff time for each analysis.
#'   }
#' }
#'
#' All calculations are performed using dplyr for maximum efficiency and are
#' stratified by simulation ID and analysis number.
#'
#' @examples
#' library(dplyr)
#'
#' # Generate trial data
#' trial_data <- simTrial(
#'   nsim = 100,
#'   n = list(
#'     control = c(A = 25, B = 112, C = 113),
#'     treatment = c(A = 25, B = 112, C = 113)
#'   ),
#'   a.time = c(0, 12.5),
#'   intensity = 40,
#'   e.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf), C = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     control = list(A = log(2) / 4.3, B = log(2) / 4.3, C = log(2) / 4.3),
#'     treatment = list(A = log(2) / 5.811, B = log(2) / 5.811, C = log(2) / 5.811)
#'   ),
#'   d.time = NULL,
#'   d.hazard = NULL,
#'   seed = 1
#' )
#'
#' # Create analysis datasets
#' analysis_data <- analysisData(trial_data, E = c(141, 246, 352))
#'
#' # Generate overall population summary
#' overall_results <- overallSummary(analysis_data, control = 1, side = 2, hr_est_method = "Cox")
#'
#' # View results for first simulation
#' print(overall_results[overall_results$simID == 1, ])
#'
#' # Summary across simulations
#' summary_stats <- overall_results %>%
#'   group_by(analysis) %>%
#'   summarise(
#'     mean_hr = mean(hazard_ratio, na.rm = TRUE),
#'     median_hr = median(hazard_ratio, na.rm = TRUE),
#'     power = mean(lr_pvalue < 0.05, na.rm = TRUE),
#'     mean_events = mean(events_total, na.rm = TRUE),
#'     .groups = 'drop'
#'   )
#' print(summary_stats)
#'
#' @seealso
#' \code{\link{analysisData}} for creating the input analysis datasets,
#' \code{\link{lrtest}} for log-rank test implementation,
#' \code{\link{esthr}} for hazard ratio estimation,
#' \code{\link{subgroupSummary}} for subgroup analysis
#'
#' @import dplyr
#' @export
overallSummary <- function(data, control = 1, side = 2, hr_est_method = "Cox") {
  # Input validation
  if (!inherits(data, c("tbl_df", "tbl", "data.frame"))) {
    stop("data must be a tibble or data.frame generated by analysisData")
  }

  required_cols <- c("simID", "analysis", "group", "tte", "event", "analysis.time")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  if (!side %in% c(1, 2)) {
    stop("side must be either 1 (one-sided) or 2 (two-sided)")
  }

  valid_methods <- c('PY', 'Pike', 'Peto', 'LR', 'Cox')
  if (!hr_est_method %in% valid_methods) {
    stop(paste("hr_est_method must be one of:", paste(valid_methods, collapse = ", ")))
  }

  # Calculate overall population statistics for each simulation and analysis
  overall_results <- data %>%
    group_by(simID, analysis) %>%
    summarise(
      # Basic summary statistics
      subgroup = "Overall",
      analysis_time = first(analysis.time),
      n_total = n(),
      n_control = sum(group == control),
      n_treatment = sum(group != control),
      events_total = sum(event),
      events_control = sum(event & group == control),
      events_treatment = sum(event & group != control),

      # Statistical tests
      lr_statistic = calculate_lr_statistic(tte, event, group, control, side),
      lr_pvalue = calculate_lr_pvalue(lr_statistic, side),
      hazard_ratio = calculate_hazard_ratio(tte, event, group, control, hr_est_method),
      hr_method = hr_est_method,

      .groups = 'drop'
    ) %>%
    # Reorder columns
    select(simID, analysis, subgroup, analysis_time, lr_statistic, lr_pvalue,
           hazard_ratio, hr_method, n_total, n_control, n_treatment,
           events_total, events_control, events_treatment) %>%
    # Sort by simID and analysis
    arrange(simID, analysis)

  return(overall_results)
}

# Helper function: Calculate log-rank statistic
calculate_lr_statistic <- function(tte, event, group, control, side) {
  # Check if we have enough data
  unique_groups <- unique(group)
  if (length(unique_groups) != 2 || sum(event) < 2) {
    return(NA_real_)
  }

  # Check if both groups have events
  events_by_group <- tapply(event, group, sum)
  if (any(events_by_group == 0)) {
    return(NA_real_)
  }

  tryCatch({
    lr_stat <- lrtest(tte, event, group, control, side)
    return(lr_stat)
  }, error = function(e) {
    return(NA_real_)
  })
}

# Helper function: Calculate log-rank p-value
calculate_lr_pvalue <- function(lr_statistic, side) {
  if (is.na(lr_statistic)) {
    return(NA_real_)
  }

  if (side == 1) {
    # One-sided test: lr_statistic is Z-score
    return(pnorm(lr_statistic))
  } else {
    # Two-sided test: lr_statistic is chi-square
    return(1 - pchisq(lr_statistic, 1))
  }
}

# Helper function: Calculate hazard ratio
calculate_hazard_ratio <- function(tte, event, group, control, hr_est_method) {
  # Check if we have enough data
  unique_groups <- unique(group)
  if (length(unique_groups) != 2) {
    return(NA_real_)
  }

  # Check if both groups have events
  events_by_group <- tapply(event, group, sum)
  if (any(events_by_group == 0)) {
    return(NA_real_)
  }

  tryCatch({
    hr_result <- esthr(tte, event, group, control, hr_est_method)
    return(hr_result$HR)
  }, error = function(e) {
    return(NA_real_)
  })
}
