# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Two-group average hazard ratio core (internal)
#'
#' Internal Rcpp core for \code{\link{ahr_fast}}. Computes the
#' Kalbfleisch-Prentice average hazard ratio over the interval from 0 to
#' \code{tau} for two groups, with the direct Greenwood-based variance of the
#' first group share \code{theta1}. The two groups' observations must each be
#' sorted in ascending time order and \code{grid} must be sorted and unique.
#'
#' @param time1 sorted right-censored times for the reference group
#' @param status1 0/1 event indicators for the reference group
#' @param time2 sorted right-censored times for the comparison group
#' @param status2 0/1 event indicators for the comparison group
#' @param grid common evaluation times (sorted, unique, including 0 and tau)
#' @return A named numeric vector with elements theta1, theta2, ahr,
#'   var.theta1, var.theta2, GL and valid.
#' @keywords internal
ahr_core <- function(time1, status1, time2, status2, grid) {
    .Call(`_FastSurvival_ahr_core`, time1, status1, time2, status2, grid)
}

#' Core average hazard with survival weight computation for one group (C++ backend)
#'
#' @description
#' Internal C++ function that computes the average hazard with survival weight
#' (AHSW) of Uno and Horiguchi for a single group, together with the building
#' blocks needed for its asymptotic variance. The average hazard on the window
#' from 0 to \code{tau} is the ratio of the cumulative event probability at
#' \code{tau} to the restricted mean survival time at \code{tau}, both based on
#' the Kaplan-Meier estimate. The function walks a pooled sorted dataset once,
#' accumulating the Nelson-Aalen increment, the Kaplan-Meier survival, the
#' running restricted mean survival time and the at-risk fraction at each
#' distinct event time at or before \code{tau}, and forms the two variance
#' sums used for the ratio (log scale) and the difference (identity scale).
#' Not intended to be called directly by users; use \code{ahsw_fast()} instead.
#'
#' @details
#' Writing F for the cumulative event probability at \code{tau}, R for the
#' restricted mean survival time at \code{tau}, R(t) for the running restricted
#' mean survival time, dH(t) for the Nelson-Aalen increment and G(t) for the
#' at-risk fraction, the average hazard is F / R and the two variance sums are
#' the sum over event times of dH(t) (kernel(t))^2 / G(t). For the average
#' hazard on the log scale the kernel is 1 / F - R(t) / R, matching the
#' \code{v_Q} term of the reference implementation, and for the average hazard
#' on the identity scale the kernel is 1 / R - F R(t) / R^2, matching the
#' \code{v_U} term. The survival function is the right-continuous Kaplan-Meier
#' product, and the running restricted mean survival time integrates the
#' left-hand survival over each grid interval, exactly as in the reference.
#'
#' @param time_sorted A numeric vector of follow-up times sorted in ascending
#'   order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param tau A numeric truncation time point.
#'
#' @return A numeric vector of length 6: \code{c(F_tau, RMST_tau, AH, v_Q, v_U,
#'   surv_tau)}, where F_tau is the cumulative event probability at \code{tau},
#'   RMST_tau is the restricted mean survival time at \code{tau}, AH is the
#'   average hazard F_tau / RMST_tau, v_Q is the variance sum on the log scale,
#'   v_U is the variance sum on the identity scale, and surv_tau is the
#'   Kaplan-Meier survival at \code{tau}. The variance sums must be divided by
#'   the group size by the caller.
#'
#' @keywords internal
ahsw_core <- function(time_sorted, event_sorted, tau) {
    .Call(`_FastSurvival_ahsw_core`, time_sorted, event_sorted, tau)
}

analysis_loop_core <- function(sim_ptr, accrual, tte, event, j, look_type, look_values, pop_col, pop_level, sub_mat, strata, use_strata, do_logrank, do_coxph, do_rmst, do_km, do_maxcombo, do_ahsw, weight_scheme, rho, gamma, t_star, mc_rho, mc_gamma, tau, t_eval) {
    .Call(`_FastSurvival_analysis_loop_core`, sim_ptr, accrual, tte, event, j, look_type, look_values, pop_col, pop_level, sub_mat, strata, use_strata, do_logrank, do_coxph, do_rmst, do_km, do_maxcombo, do_ahsw, weight_scheme, rho, gamma, t_star, mc_rho, mc_gamma, tau, t_eval)
}

#' Core max-combo weighted log-rank computation on pooled sorted vectors (C++ backend)
#'
#' @description
#' Internal C++ function that computes a vector of Fleming-Harrington weighted
#' log-rank numerators and their full covariance matrix in a single pass over a
#' pooled sorted dataset. Each weight is a Fleming-Harrington G(rho, gamma)
#' weight evaluated from the left-continuous pooled Kaplan-Meier estimate, with
#' the pairs supplied through \code{rho_vec} and \code{gamma_vec}. The variance
#' increment at each event time does not depend on the weight, so it is computed
#' once and reused for every numerator and every pair of weights. The diagonal
#' of the returned covariance matrix holds the per-scheme variances, and the
#' off-diagonal entries hold the between-scheme covariances used to form the
#' correlation matrix for the max-combo p-value. Tied event times are processed
#' atomically. Not intended to be called directly by users; use the max-combo
#' R wrapper instead.
#'
#' @details
#' For a weight indexed by k the numerator is \code{U_k = sum w_k (O1 - E1)} and
#' the variance is \code{V_kk = sum w_k^2 v}, where \code{v} is the
#' hypergeometric variance increment \code{d n1 (n - n1) (n - d) /
#' (n^2 (n - 1))}. The between-scheme covariance is \code{V_ab = sum w_a w_b v}.
#' Here \code{S_minus} is the left-continuous pooled Kaplan-Meier estimate just
#' prior to each event time, initialized at 1, and the weight is
#' \code{S_minus^rho (1 - S_minus)^gamma}. The convention is the same as the
#' single-scheme weighted core: the numerator is negative when the treatment
#' group is favored.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#' @param rho_vec A numeric vector of Fleming-Harrington first parameters, one
#'   per weight scheme.
#' @param gamma_vec A numeric vector of Fleming-Harrington second parameters,
#'   one per weight scheme, aligned with \code{rho_vec}.
#'
#' @return A list with three elements: \code{O1}, the observed number of events
#'   in the treatment group; \code{U}, a numeric vector of weighted log-rank
#'   numerators (one per weight scheme); and \code{V}, the numeric covariance
#'   matrix of the numerators.
#'
#' @keywords internal
combo_logrank_core <- function(time_sorted, event_sorted, j_sorted, rho_vec, gamma_vec) {
    .Call(`_FastSurvival_combo_logrank_core`, time_sorted, event_sorted, j_sorted, rho_vec, gamma_vec)
}

#' Core Kaplan-Meier computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the Kaplan-Meier survival estimate and
#' the Greenwood variance sum at a specified time point. Binary search locates
#' the cutoff index; a single left-to-right scan accumulates the KM product
#' and Greenwood sum over event positions only. Accepts the event vector as
#' a numeric (double) vector to avoid an \code{as.integer()} copy in R.
#' Uses \code{std::log1p(-1/n_risk)} for the KM log-product, which is more
#' accurate than \code{std::log(1 - 1/n_risk)} near n_risk = 1 and avoids one
#' subtraction per event. Not intended to be called directly by users; use
#' \code{survfit_fast()} instead.
#'
#' @param t_sorted A numeric vector of follow-up times sorted in ascending
#'   order.
#' @param e_sorted A numeric vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{t_sorted}. Accepted as numeric to
#'   avoid an integer-conversion copy on the R side.
#' @param t_eval A single numeric value specifying the evaluation time point.
#'
#' @return A numeric vector of length 2: \code{c(surv, gw_sum)}, where
#'   \code{surv} is the KM estimate and \code{gw_sum} is the Greenwood
#'   variance sum used to compute SE[S(t)] = surv * sqrt(gw_sum).
#'   Returns \code{c(1.0, 0.0)} when no events occur up to \code{t_eval}.
#'
#' @keywords internal
km_core <- function(t_sorted, e_sorted, t_eval) {
    .Call(`_FastSurvival_km_core`, t_sorted, e_sorted, t_eval)
}

#' Core log-rank computation on pooled sorted vectors (C++ backend)
#'
#' @description
#' Internal C++ function that computes O1, E1, and V1 for the log-rank test
#' directly from a pooled sorted dataset and a group indicator. Eliminates
#' the R-level group-splitting copies (\code{time[is1]}, \code{time[!is1]},
#' \code{event[is1]}, \code{event[!is1]}) of the previous design by walking
#' the pooled vector once and updating per-group at-risk counters in C++.
#' Tied event times are processed atomically. Not intended to be called
#' directly by users; use \code{survdiff_fast()} instead.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#'
#' @return A numeric vector of length 3: \code{c(O1, E1, V1)}.
#'
#' @keywords internal
logrank_core <- function(time_sorted, event_sorted, j_sorted) {
    .Call(`_FastSurvival_logrank_core`, time_sorted, event_sorted, j_sorted)
}

milestone_core <- function(time, status, grp, tau, presorted) {
    .Call(`_FastSurvival_milestone_core`, time, status, grp, tau, presorted)
}

#' Core PiHE hazard ratio computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the Pike-Halley Estimator (PiHE) for
#' the hazard ratio. Accepts pooled sorted vectors plus an integer group
#' indicator, performs group splitting and the two-pointer merge scan
#' entirely in C++, and returns the quantities needed for the Halley
#' correction and Wald interval. Not intended to be called directly by
#' users; use \code{coxph_fast()} instead.
#'
#' Implementation notes: Pass 1 accumulates pooled scalars
#' (O_T, O_C, E_T, E_C) and stores per-distinct-event-time summaries in a
#' single struct array (better cache locality than four parallel vectors)
#' with a single \code{reserve(n)} call (no event-count prepass over the
#' input). Pass 2 walks the saved summaries once at the Pike anchor
#' theta_0 to compute U_0, I_0, and J_0.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#'
#' @return A numeric vector of length 4: \code{c(theta_0, U_0, I_0, J_0)}.
#'   Returns a length-4 vector of \code{NA_real_} when the estimate cannot
#'   be computed.
#'
#' @keywords internal
pihe_core <- function(time_sorted, event_sorted, j_sorted) {
    .Call(`_FastSurvival_pihe_core`, time_sorted, event_sorted, j_sorted)
}

#' Core restricted mean survival time computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the restricted mean survival time
#' (RMST) and its Greenwood-type variance for a single group up to a horizon
#' \code{tau}. A single left-to-right scan over the sorted data accumulates
#' the Kaplan-Meier product and the area under the survival step function,
#' storing one summary per distinct event time (the cumulative area to the
#' left of that time and the Greenwood increment). A second short pass over
#' the saved summaries forms the variance as a sum of squared right-side
#' areas weighted by the Greenwood increments. Accepts the event vector as a
#' numeric (double) vector to avoid an \code{as.integer()} copy in R. Not
#' intended to be called directly by users; use \code{rmst_fast()} instead.
#'
#' @param t_sorted A numeric vector of follow-up times sorted in ascending
#'   order.
#' @param e_sorted A numeric vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{t_sorted}. Accepted as numeric to
#'   avoid an integer-conversion copy on the R side.
#' @param tau A single numeric value specifying the restriction horizon.
#'
#' @return A numeric vector of length 2: \code{c(rmst, var_rmst)}, where
#'   \code{rmst} is the restricted mean survival time and \code{var_rmst} is
#'   its variance, so that SE[RMST] = sqrt(var_rmst). Returns
#'   \code{c(tau, 0.0)} when no events occur up to \code{tau}.
#'
#' @keywords internal
rmst_core <- function(t_sorted, e_sorted, tau) {
    .Call(`_FastSurvival_rmst_core`, t_sorted, e_sorted, tau)
}

#' Core robust modestly-weighted log-rank computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes, in a single pass over a pooled sorted
#' dataset, the two component statistics of the robust modestly-weighted (rMW)
#' log-rank test of Magirr and Ohrn together with their null covariance. The
#' first component is the standard log-rank statistic (weight one at every
#' event time); the second is a modestly-weighted log-rank statistic with
#' weight \code{min(1 / S(t-), 1 / s_star)}, where \code{S(t-)} is the
#' left-continuous pooled Kaplan-Meier estimate just prior to each event time
#' and \code{s_star} is a survival-probability threshold. The rMW test
#' rejects for an extreme value of the maximum of the two standardized
#' components, so the covariance of the two numerators under the null is
#' required to recover the joint distribution. Tied event times are processed
#' atomically. Not intended to be called directly by users; use
#' \code{rmw_fast()} instead.
#'
#' @details
#' The standard log-rank numerator is \code{U_lr = sum (d1 - e1)} with variance
#' \code{V_lr = sum var_d}, where \code{d1} is the number of treatment-group
#' events at an event time, \code{e1 = d n1 / n} is the expected count, and
#' \code{var_d = d n1 n0 (n - d) / (n^2 (n - 1))} is the hypergeometric
#' variance of \code{d1}. The modestly-weighted numerator is
#' \code{U_mw = sum w (d1 - e1)} with variance \code{V_mw = sum w^2 var_d}.
#' Because the standard log-rank weight is one, the null covariance of the two
#' numerators reduces to \code{C = sum w var_d}. The modestly-weighted weight
#' is capped at \code{1 / s_star}, a constant, so unlike the timepoint
#' parameterization used by \code{weighted_logrank_core} no first pass is
#' needed and all quantities accumulate in one scan. When \code{s_star} is not
#' positive the cap is treated as infinite, giving the uncapped
#' \code{1 / S(t-)} weight. Setting \code{s_star = 1} caps the weight at one,
#' so the modestly-weighted component equals the standard log-rank component
#' and the two are perfectly correlated.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#' @param s_star A numeric survival-probability threshold for the
#'   modestly-weighted component. The weight is capped at \code{1 / s_star},
#'   so a value of \code{0.5} caps the weight at 2.
#'
#' @return A numeric vector of length 6:
#'   \code{c(O1, U_lr, V_lr, U_mw, V_mw, C)}, where O1 is the observed number
#'   of events in the treatment group, U_lr and V_lr are the standard log-rank
#'   numerator and variance, U_mw and V_mw are the modestly-weighted numerator
#'   and variance, and C is the null covariance of the two numerators.
#'
#' @keywords internal
rmw_core <- function(time_sorted, event_sorted, j_sorted, s_star) {
    .Call(`_FastSurvival_rmw_core`, time_sorted, event_sorted, j_sorted, s_star)
}

simdata_core_full <- function(nsim, n_grp, a_time, cum_p_a, n_cell, e_haz_c, e_fin_c, e_cum_c, e_haz_t, e_fin_t, e_cum_t, has_dropout, d_haz_c, d_fin_c, d_cum_c, d_haz_t, d_fin_t, d_cum_t, cum_prev_c, cum_prev_t, level_table_c, level_table_t, sub_names, fixed_alloc, fixed_counts_c, fixed_counts_t) {
    .Call(`_FastSurvival_simdata_core_full`, nsim, n_grp, a_time, cum_p_a, n_cell, e_haz_c, e_fin_c, e_cum_c, e_haz_t, e_fin_t, e_cum_t, has_dropout, d_haz_c, d_fin_c, d_cum_c, d_haz_t, d_fin_t, d_cum_t, cum_prev_c, cum_prev_t, level_table_c, level_table_t, sub_names, fixed_alloc, fixed_counts_c, fixed_counts_t)
}

#' Core stratified log-rank computation on stratum-blocked sorted vectors
#'
#' @description
#' Internal C++ function that computes the stratified log-rank totals O1, E1,
#' and V1 from a dataset sorted by stratum first and by time within stratum.
#' Each stratum is processed as an independent contiguous block using the
#' same single-pass two-group scan as \code{logrank_core}, and the per-stratum
#' O1, E1, and V1 are accumulated into the returned totals. Tied event times
#' are processed atomically within each stratum. A stratum that contains only
#' one group contributes zero to all three totals, matching the behavior of
#' \code{\link[survival]{survdiff}} with a \code{strata()} term. Not intended
#' to be called directly by users; use \code{survdiff_fast()} with the
#' \code{strata} argument instead.
#'
#' @param time_sorted A numeric vector of follow-up times sorted by stratum
#'   first and by ascending time within each stratum.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#' @param strata_sorted An integer vector of stratum identifiers, aligned with
#'   \code{time_sorted}. Rows of the same stratum must be contiguous, which is
#'   guaranteed when the data are sorted by stratum first.
#'
#' @return A numeric vector of length 3: \code{c(O1, E1, V1)}, the stratified
#'   observed events, expected events, and variance for the treatment group.
#'
#' @keywords internal
stratified_logrank_core <- function(time_sorted, event_sorted, j_sorted, strata_sorted) {
    .Call(`_FastSurvival_stratified_logrank_core`, time_sorted, event_sorted, j_sorted, strata_sorted)
}

#' Core stratified weighted log-rank computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the stratified weighted log-rank totals
#' from a dataset sorted by stratum first and by time within stratum. Each
#' stratum is processed as an independent weighted log-rank test using the same
#' logic as \code{weighted_logrank_core}, with weights derived from the
#' within-stratum pooled Kaplan-Meier estimate, and the per-stratum numerator U
#' and variance V are accumulated into the returned totals. The overall
#' statistic is Z = sum U / sqrt(sum V). This matches the stratified weighted
#' log-rank test of Magirr, which sums the per-stratum U and V and standardizes
#' once. Not intended to be called directly by users; use
#' \code{survdiff_fast()} with both \code{weight} and \code{strata} instead.
#'
#' @details
#' The scheme codes match \code{weighted_logrank_core}: 0 = Fleming-Harrington
#' G(rho, gamma); 1 = modestly-weighted with cap \code{1 / S(t_star)} computed
#' within each stratum; 2 = Gehan-Breslow; 3 = Tarone-Ware. The left-continuous
#' pooled Kaplan-Meier estimate is restarted at 1 at the beginning of every
#' stratum, so the weights of each stratum depend only on that stratum's
#' pooled data. For the modestly-weighted scheme the weight cap is determined
#' in a first pass within each stratum before accumulation.
#'
#' @param time_sorted A numeric vector of follow-up times sorted by stratum
#'   first and by ascending time within each stratum.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#' @param strata_sorted An integer vector of stratum identifiers, aligned with
#'   \code{time_sorted}. Rows of the same stratum must be contiguous.
#' @param scheme An integer weight-scheme code: 0 = Fleming-Harrington,
#'   1 = modestly-weighted, 2 = Gehan-Breslow, 3 = Tarone-Ware.
#' @param rho A numeric Fleming-Harrington first parameter (scheme 0).
#' @param gamma A numeric Fleming-Harrington second parameter (scheme 0).
#' @param t_star A numeric timepoint for the modestly-weighted scheme
#'   (scheme 1).
#'
#' @return A numeric vector of length 3: \code{c(O1, U, V)}, where O1 is the
#'   pooled observed number of events in the treatment group, U is the summed
#'   weighted numerator, and V is the summed weighted variance.
#'
#' @keywords internal
stratified_weighted_logrank_core <- function(time_sorted, event_sorted, j_sorted, strata_sorted, scheme, rho, gamma, t_star) {
    .Call(`_FastSurvival_stratified_weighted_logrank_core`, time_sorted, event_sorted, j_sorted, strata_sorted, scheme, rho, gamma, t_star)
}

#' Core weighted log-rank computation on pooled sorted vectors (C++ backend)
#'
#' @description
#' Internal C++ function that computes the weighted log-rank numerator U and
#' variance V directly from a pooled sorted dataset and a group indicator.
#' Four weight schemes are supported, selected by \code{scheme}: Fleming-
#' Harrington G(rho, gamma), the modestly-weighted log-rank test, Gehan-
#' Breslow, and Tarone-Ware. The weights are functions of the left-continuous
#' pooled Kaplan-Meier estimate (for Fleming-Harrington and the modestly-
#' weighted test) or of the at-risk count (for Gehan-Breslow and Tarone-Ware).
#' Tied event times are processed atomically. Not intended to be called
#' directly by users; use \code{survdiff_fast()} with the \code{weight}
#' argument instead.
#'
#' @details
#' The scheme codes are: 0 = Fleming-Harrington G(rho, gamma) with weight
#' \code{S_minus^rho * (1 - S_minus)^gamma}; 1 = modestly-weighted log-rank
#' with weight \code{min(1 / S_minus, max_weight)}, where \code{max_weight}
#' is the reciprocal of the smallest right-continuous pooled Kaplan-Meier
#' value at or after \code{t_star} (and is 1 when \code{t_star = 0});
#' 2 = Gehan-Breslow with weight \code{n_j}; 3 = Tarone-Ware with weight
#' \code{sqrt(n_j)}. Here \code{S_minus} is the left-continuous pooled
#' Kaplan-Meier estimate just prior to each event time, initialized at 1.
#' The modestly-weighted scheme requires the largest weight to be known before
#' accumulation, so its \code{max_weight} is obtained in a first pass over the
#' event times; the other schemes accumulate in a single pass.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#' @param scheme An integer weight-scheme code: 0 = Fleming-Harrington,
#'   1 = modestly-weighted, 2 = Gehan-Breslow, 3 = Tarone-Ware.
#' @param rho A numeric Fleming-Harrington first parameter (used when
#'   \code{scheme = 0}).
#' @param gamma A numeric Fleming-Harrington second parameter (used when
#'   \code{scheme = 0}).
#' @param t_star A numeric timepoint for the modestly-weighted scheme (used
#'   when \code{scheme = 1}).
#'
#' @return A numeric vector of length 3: \code{c(O1, U, V)}, where O1 is the
#'   observed number of events in the treatment group, U is the weighted
#'   log-rank numerator sum w (O1 - E1), and V is the weighted variance.
#'
#' @keywords internal
weighted_logrank_core <- function(time_sorted, event_sorted, j_sorted, scheme, rho, gamma, t_star) {
    .Call(`_FastSurvival_weighted_logrank_core`, time_sorted, event_sorted, j_sorted, scheme, rho, gamma, t_star)
}

