# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Core Kaplan-Meier computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the Kaplan-Meier survival estimate and
#' the Greenwood variance sum at a specified time point. Binary search locates
#' the cutoff index; a single left-to-right scan accumulates the KM product
#' and Greenwood sum over event positions only. Accepts the event vector as
#' a numeric (double) vector to avoid an \code{as.integer()} copy in R.
#' Uses \code{std::log1p(-1/n_risk)} for the KM log-product, which is more
#' accurate than \code{std::log(1 - 1/n_risk)} near n_risk = 1 and avoids one
#' subtraction per event. Not intended to be called directly by users; use
#' \code{survfit_fast()} instead.
#'
#' @param t_sorted A numeric vector of follow-up times sorted in ascending
#'   order.
#' @param e_sorted A numeric vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{t_sorted}. Accepted as numeric to
#'   avoid an integer-conversion copy on the R side.
#' @param t_eval A single numeric value specifying the evaluation time point.
#'
#' @return A numeric vector of length 2: \code{c(surv, gw_sum)}, where
#'   \code{surv} is the KM estimate and \code{gw_sum} is the Greenwood
#'   variance sum used to compute SE[S(t)] = surv * sqrt(gw_sum).
#'   Returns \code{c(1.0, 0.0)} when no events occur up to \code{t_eval}.
#'
#' @keywords internal
km_core <- function(t_sorted, e_sorted, t_eval) {
    .Call(`_FastSurvival_km_core`, t_sorted, e_sorted, t_eval)
}

#' Core log-rank computation on pooled sorted vectors (C++ backend)
#'
#' @description
#' Internal C++ function that computes O1, E1, and V1 for the log-rank test
#' directly from a pooled sorted dataset and a group indicator. Eliminates
#' the R-level group-splitting copies (\code{time[is1]}, \code{time[!is1]},
#' \code{event[is1]}, \code{event[!is1]}) of the previous design by walking
#' the pooled vector once and updating per-group at-risk counters in C++.
#' Tied event times are processed atomically. Not intended to be called
#' directly by users; use \code{survdiff_fast()} instead.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#'
#' @return A numeric vector of length 3: \code{c(O1, E1, V1)}.
#'
#' @keywords internal
logrank_core <- function(time_sorted, event_sorted, j_sorted) {
    .Call(`_FastSurvival_logrank_core`, time_sorted, event_sorted, j_sorted)
}

#' Core PiHE hazard ratio computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the Pike-Halley Estimator (PiHE) for
#' the hazard ratio. Accepts pooled sorted vectors plus an integer group
#' indicator, performs group splitting and the two-pointer merge scan
#' entirely in C++, and returns the quantities needed for the Halley
#' correction and Wald interval. Not intended to be called directly by
#' users; use \code{coxph_fast()} instead.
#'
#' Implementation notes: Pass 1 accumulates pooled scalars
#' (O_T, O_C, E_T, E_C) and stores per-distinct-event-time summaries in a
#' single struct array (better cache locality than four parallel vectors)
#' with a single \code{reserve(n)} call (no event-count prepass over the
#' input). Pass 2 walks the saved summaries once at the Pike anchor
#' theta_0 to compute U_0, I_0, and J_0.
#'
#' @param time_sorted A numeric vector of pooled follow-up times sorted in
#'   ascending order.
#' @param event_sorted An integer vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{time_sorted}.
#' @param j_sorted An integer vector of group indicators (1 = treatment,
#'   0 = control), aligned with \code{time_sorted}.
#'
#' @return A numeric vector of length 4: \code{c(theta_0, U_0, I_0, J_0)}.
#'   Returns a length-4 vector of \code{NA_real_} when the estimate cannot
#'   be computed.
#'
#' @keywords internal
pihe_core <- function(time_sorted, event_sorted, j_sorted) {
    .Call(`_FastSurvival_pihe_core`, time_sorted, event_sorted, j_sorted)
}

#' Core restricted mean survival time computation (C++ backend)
#'
#' @description
#' Internal C++ function that computes the restricted mean survival time
#' (RMST) and its Greenwood-type variance for a single group up to a horizon
#' \code{tau}. A single left-to-right scan over the sorted data accumulates
#' the Kaplan-Meier product and the area under the survival step function,
#' storing one summary per distinct event time (the cumulative area to the
#' left of that time and the Greenwood increment). A second short pass over
#' the saved summaries forms the variance as a sum of squared right-side
#' areas weighted by the Greenwood increments. Accepts the event vector as a
#' numeric (double) vector to avoid an \code{as.integer()} copy in R. Not
#' intended to be called directly by users; use \code{rmst_fast()} instead.
#'
#' @param t_sorted A numeric vector of follow-up times sorted in ascending
#'   order.
#' @param e_sorted A numeric vector of event indicators (1 = event,
#'   0 = censored), aligned with \code{t_sorted}. Accepted as numeric to
#'   avoid an integer-conversion copy on the R side.
#' @param tau A single numeric value specifying the restriction horizon.
#'
#' @return A numeric vector of length 2: \code{c(rmst, var_rmst)}, where
#'   \code{rmst} is the restricted mean survival time and \code{var_rmst} is
#'   its variance, so that SE[RMST] = sqrt(var_rmst). Returns
#'   \code{c(tau, 0.0)} when no events occur up to \code{tau}.
#'
#' @keywords internal
rmst_core <- function(t_sorted, e_sorted, tau) {
    .Call(`_FastSurvival_rmst_core`, t_sorted, e_sorted, tau)
}

rpiece_unif_cpp <- function(n, a_time, cum_p) {
    .Call(`_FastSurvival_rpiece_unif_cpp`, n, a_time, cum_p)
}

rpiece_exp_cpp <- function(n, hazard, fin_time, cum_haz) {
    .Call(`_FastSurvival_rpiece_exp_cpp`, n, hazard, fin_time, cum_haz)
}

interleave_groups <- function(df_ctrl, df_trt, nsim, n_ctrl, n_trt) {
    .Call(`_FastSurvival_interleave_groups`, df_ctrl, df_trt, nsim, n_ctrl, n_trt)
}

