#' Subgroup statistical analysis summary for clinical trial data
#'
#' This function performs subgroup statistical analysis on clinical trial data
#' generated by \code{\link{analysisData}}. It calculates hazard ratios, patient counts,
#' and event counts for each subgroup using data.table for maximum performance.
#'
#' @param data A data.table containing analysis data generated by \code{\link{analysisData}}.
#'   Must contain columns: simID, analysis, group, subgroup, tte, event.
#' @param control A numeric value indicating which value in \code{group} represents
#'   the control group. Default is 1.
#' @param hr_est_method A character string specifying the hazard ratio estimation method.
#'   Must be one of "PY", "Pike", "Peto", "LR", or "Cox". Default is "Cox".
#'
#' @return A data.table containing subgroup analysis results with the following columns:
#' \describe{
#'   \item{simID}{Simulation iteration ID}
#'   \item{analysis}{Analysis number}
#'   \item{subgroup}{Subgroup indicator}
#'   \item{hazard_ratio}{Estimated hazard ratio}
#'   \item{hr_method}{Method used for hazard ratio estimation}
#'   \item{n_total}{Total number of patients in subgroup}
#'   \item{n_control}{Number of patients in control group within subgroup}
#'   \item{n_treatment}{Number of patients in treatment group within subgroup}
#'   \item{events_total}{Total number of events in subgroup}
#'   \item{events_control}{Number of events in control group within subgroup}
#'   \item{events_treatment}{Number of events in treatment group within subgroup}
#' }
#'
#' @details
#' This function provides subgroup summary of clinical trial results by:
#'
#' \describe{
#'   \item{Hazard Ratio Estimation}{
#'     Calculates hazard ratios using \code{\link{FastHRest}} for each subgroup
#'     using the specified method.
#'   }
#'   \item{Patient and Event Counts}{
#'     Summarizes patient numbers and event numbers by group for each subgroup.
#'   }
#' }
#'
#' All calculations are performed using data.table for maximum efficiency and are
#' stratified by simulation ID, analysis number, and subgroup.
#'
#' @examples
#' library(data.table)
#'
#' # Generate trial data with subgroups
#' trial_data <- simTrial(
#'   nsim = 50,
#'   N = list(
#'     control = c(A = 50, B = 50),
#'     treatment = c(A = 50, B = 50)
#'   ),
#'   a.time = list(
#'     control = list(A = c(0, 18), B = c(0, 18)),
#'     treatment = list(A = c(0, 18), B = c(0, 18))
#'   ),
#'   intensity = list(
#'     control = list(A = 50/18, B = 50/18),
#'     treatment = list(A = 50/18, B = 50/18)
#'   ),
#'   e.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     control = list(A = 0.08, B = 0.12),
#'     treatment = list(A = 0.05, B = 0.08)
#'   ),
#'   d.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   d.hazard = list(
#'     control = list(A = 0.01, B = 0.01),
#'     treatment = list(A = 0.01, B = 0.01)
#'   ),
#'   seed = 123
#' )
#'
#' # Create analysis datasets
#' analysis_data <- analysisData(trial_data, E = c(50, 100, 150))
#'
#' # Generate subgroup summary
#' subgroup_results <- subgroupSummary(analysis_data, control = 1, hr_est_method = "Cox")
#'
#' # View results for first simulation, first analysis
#' print(subgroup_results[simID == 1 & analysis == 1])
#'
#' @seealso
#' \code{\link{analysisData}} for creating the input analysis datasets,
#' \code{\link{FastHRest}} for hazard ratio estimation,
#' \code{\link{overallSummary}} for overall population analysis
#'
#' @import data.table
#' @export
subgroupSummary <- function(data, control = 1, hr_est_method = "Cox") {
  # Input validation
  if (!is.data.table(data)) {
    data <- as.data.table(data)
  }

  required_cols <- c("simID", "analysis", "group", "subgroup", "tte", "event")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  valid_methods <- c('PY', 'Pike', 'Peto', 'LR', 'Cox')
  if (!hr_est_method %in% valid_methods) {
    stop(paste("hr_est_method must be one of:", paste(valid_methods, collapse = ", ")))
  }

  # Set key for optimal performance
  setkeyv(data, c("simID", "analysis", "subgroup"))

  # Pre-compute group indicators for efficiency
  data[, `:=`(
    is_control = as.integer(group == control),
    is_treatment = as.integer(group != control)
  )]

  # Helper function for hazard ratio computation
  compute_hr <- function(tte_vec, event_vec, group_vec) {
    if (length(unique(group_vec)) != 2) {
      return(NA_real_)
    }

    # Check if both groups have events
    events_by_group <- tapply(event_vec, group_vec, sum)
    if (any(events_by_group == 0)) {
      return(NA_real_)
    }

    tryCatch({
      hr_result <- FastHRest(tte_vec, event_vec, group_vec, control, hr_est_method)
      hr_result$HR
    }, error = function(e) {
      NA_real_
    })
  }

  # Subgroup analysis using data.table operations
  subgroup_results <- data[, {
    list(
      n_total = .N,
      n_control = sum(is_control),
      n_treatment = sum(is_treatment),
      events_total = sum(event),
      events_control = sum(event * is_control),
      events_treatment = sum(event * is_treatment),
      hazard_ratio = compute_hr(tte, event, group)
    )
  }, by = .(simID, analysis, subgroup)]

  # Add hr_method column
  subgroup_results[, hr_method := hr_est_method]

  # Remove temporary columns from original data
  data[, `:=`(is_control = NULL, is_treatment = NULL)]

  # Set optimal column order
  setcolorder(subgroup_results, c("simID", "analysis", "subgroup", "hazard_ratio", "hr_method",
                                  "n_total", "n_control", "n_treatment",
                                  "events_total", "events_control", "events_treatment"))

  # Sort results for consistency
  setorderv(subgroup_results, c("simID", "analysis", "subgroup"))

  return(subgroup_results)
}
