#' Subgroup statistical analysis summary for clinical trial data
#'
#' This function performs subgroup statistical analysis on clinical trial data
#' generated by \code{\link{analysisData}}. It calculates hazard ratios, patient counts,
#' and event counts for each subgroup using dplyr for maximum performance.
#'
#' @param data A tibble containing analysis data generated by \code{\link{analysisData}}.
#'   Must contain columns: simID, analysis, group, subgroup, tte, event.
#' @param control A numeric value indicating which value in \code{group} represents
#'   the control group. Default is 1.
#' @param hr_est_method A character string specifying the hazard ratio estimation method.
#'   Must be one of "PY", "Pike", "Peto", "LR", or "Cox". Default is "Cox".
#'
#' @return A tibble containing subgroup analysis results with the following columns:
#' \describe{
#'   \item{simID}{Simulation iteration ID}
#'   \item{analysis}{Analysis number}
#'   \item{subgroup}{Subgroup indicator}
#'   \item{hazard_ratio}{Estimated hazard ratio}
#'   \item{hr_method}{Method used for hazard ratio estimation}
#'   \item{n_total}{Total number of patients in subgroup}
#'   \item{n_control}{Number of patients in control group within subgroup}
#'   \item{n_treatment}{Number of patients in treatment group within subgroup}
#'   \item{events_total}{Total number of events in subgroup}
#'   \item{events_control}{Number of events in control group within subgroup}
#'   \item{events_treatment}{Number of events in treatment group within subgroup}
#' }
#'
#' @details
#' This function provides subgroup summary of clinical trial results by:
#'
#' \describe{
#'   \item{Hazard Ratio Estimation}{
#'     Calculates hazard ratios using \code{\link{esthr}} for each subgroup
#'     using the specified method.
#'   }
#'   \item{Patient and Event Counts}{
#'     Summarizes patient numbers and event numbers by group for each subgroup.
#'   }
#' }
#'
#' All calculations are performed using dplyr for maximum efficiency and are
#' stratified by simulation ID, analysis number, and subgroup.
#'
#' @examples
#' library(dplyr)
#'
#' # Generate trial data with subgroups
#' trial_data <- simTrial(
#'   nsim = 50,
#'   N = list(
#'     control = c(A = 50, B = 50),
#'     treatment = c(A = 50, B = 50)
#'   ),
#'   a.time = c(0, 18),
#'   intensity = 200/18,
#'   e.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     control = list(A = 0.08, B = 0.12),
#'     treatment = list(A = 0.05, B = 0.08)
#'   ),
#'   d.time = NULL,  # No dropout
#'   d.hazard = NULL
#' )
#'
#' # Create analysis datasets
#' analysis_data <- analysisData(trial_data, E = c(50, 100, 150))
#'
#' # Generate subgroup summary
#' subgroup_results <- subgroupSummary(analysis_data, control = 1, hr_est_method = "Cox")
#'
#' # View results for first simulation, first analysis
#' print(subgroup_results[subgroup_results$simID == 1 & subgroup_results$analysis == 1, ])
#'
#' @seealso
#' \code{\link{analysisData}} for creating the input analysis datasets,
#' \code{\link{esthr}} for hazard ratio estimation,
#' \code{\link{overallSummary}} for overall population analysis
#'
#' @import dplyr
#' @export
subgroupSummary <- function(data, control = 1, hr_est_method = "Cox") {
  # Input validation
  if (!inherits(data, c("tbl_df", "tbl", "data.frame"))) {
    stop("data must be a tibble or data.frame generated by analysisData")
  }

  required_cols <- c("simID", "analysis", "group", "subgroup", "tte", "event")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  # Check if subgroup column exists and has non-NA values
  if (!"subgroup" %in% names(data)) {
    stop("subgroup column is required for subgroup analysis")
  }

  if (all(is.na(data$subgroup))) {
    stop("No subgroup information found in the data")
  }

  valid_methods <- c('PY', 'Pike', 'Peto', 'LR', 'Cox')
  if (!hr_est_method %in% valid_methods) {
    stop(paste("hr_est_method must be one of:", paste(valid_methods, collapse = ", ")))
  }

  # Calculate subgroup statistics for each simulation, analysis, and subgroup
  subgroup_results <- data %>%
    # Filter out rows with missing subgroup information
    filter(!is.na(subgroup)) %>%
    group_by(simID, analysis, subgroup) %>%
    summarise(
      # Basic summary statistics
      n_total = n(),
      n_control = sum(group == control),
      n_treatment = sum(group != control),
      events_total = sum(event),
      events_control = sum(event & group == control),
      events_treatment = sum(event & group != control),

      # Hazard ratio estimation
      hazard_ratio = calculate_subgroup_hazard_ratio(tte, event, group, control, hr_est_method),
      hr_method = hr_est_method,

      .groups = 'drop'
    ) %>%
    # Reorder columns
    select(simID, analysis, subgroup, hazard_ratio, hr_method, n_total,
           n_control, n_treatment, events_total, events_control, events_treatment) %>%
    # Sort by simID, analysis, and subgroup
    arrange(simID, analysis, subgroup)

  return(subgroup_results)
}

# Helper function: Calculate hazard ratio for subgroup
calculate_subgroup_hazard_ratio <- function(tte, event, group, control, hr_est_method) {
  # Check if we have enough data
  unique_groups <- unique(group)
  if (length(unique_groups) != 2) {
    return(NA_real_)
  }

  # Check if both groups have events
  events_by_group <- tapply(event, group, sum)
  if (any(events_by_group == 0)) {
    return(NA_real_)
  }

  # Check if we have enough patients in each group
  patients_by_group <- table(group)
  if (any(patients_by_group < 2)) {
    return(NA_real_)
  }

  tryCatch({
    hr_result <- esthr(tte, event, group, control, hr_est_method)
    return(hr_result$HR)
  }, error = function(e) {
    return(NA_real_)
  })
}
