#' Comprehensive statistical analysis summary for clinical trial data
#'
#' This function performs comprehensive statistical analysis on clinical trial data
#' generated by \code{\link{analysisData}}. It calculates log-rank test statistics,
#' hazard ratios, patient counts, event counts, and analysis times for both overall
#' population and subgroups using data.table for maximum performance.
#'
#' @param data A data.table containing analysis data generated by \code{\link{analysisData}}.
#'   Must contain columns: simID, analysis, group, tte, event, analysis.time.
#'   May optionally contain subgroup column for subgroup analysis.
#' @param control A numeric value indicating which value in \code{group} represents
#'   the control group. Default is 1.
#' @param hr_method A character string specifying the hazard ratio estimation method.
#'   Must be one of "PY", "Pike", "Peto", "LR", or "Cox". Default is "Cox".
#'
#' @return A data.table containing comprehensive analysis results with the following columns:
#' \describe{
#'   \item{simID}{Simulation iteration ID}
#'   \item{analysis}{Analysis number}
#'   \item{subgroup}{Subgroup indicator ("Overall" for overall population, subgroup names for subgroups)}
#'   \item{analysis_time}{Analysis cutoff time (calendar time from study start)}
#'   \item{lr_statistic}{Log-rank test chi-square statistic (overall population only, NA for subgroups)}
#'   \item{lr_pvalue}{Log-rank test p-value (overall population only, NA for subgroups)}
#'   \item{hazard_ratio}{Estimated hazard ratio}
#'   \item{hr_method}{Method used for hazard ratio estimation}
#'   \item{n_total}{Total number of patients}
#'   \item{n_control}{Number of patients in control group}
#'   \item{n_treatment}{Number of patients in treatment group}
#'   \item{events_total}{Total number of events}
#'   \item{events_control}{Number of events in control group}
#'   \item{events_treatment}{Number of events in treatment group}
#' }
#'
#' @details
#' This function provides a comprehensive summary of clinical trial results by:
#'
#' \describe{
#'   \item{Log-rank Test}{
#'     Performs log-rank test using \code{\link{FastLRtest}} for the overall population
#'     at each analysis timepoint. Returns chi-square statistic and p-value.
#'   }
#'   \item{Hazard Ratio Estimation}{
#'     Calculates hazard ratios using \code{\link{FastHRest}} for both overall population
#'     and each subgroup using the specified method.
#'   }
#'   \item{Patient Counts}{
#'     Summarizes total patient numbers by group for overall population and subgroups.
#'   }
#'   \item{Event Counts}{
#'     Summarizes total event numbers by group for overall population and subgroups.
#'   }
#'   \item{Analysis Time}{
#'     Records the analysis cutoff time for each analysis.
#'   }
#' }
#'
#' All calculations are performed using data.table for maximum efficiency and are
#' stratified by simulation ID and analysis number.
#'
#' @examples
#' library(data.table)
#'
#' # Generate trial data with subgroups
#' trial_data <- simTrial(
#'   nsim = 50,
#'   N = list(
#'     control = c(A = 50, B = 50),
#'     treatment = c(A = 50, B = 50)
#'   ),
#'   a.time = list(
#'     control = list(A = c(0, 18), B = c(0, 18)),
#'     treatment = list(A = c(0, 18), B = c(0, 18))
#'   ),
#'   intensity = list(
#'     control = list(A = 50/18, B = 50/18),
#'     treatment = list(A = 50/18, B = 50/18)
#'   ),
#'   e.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     control = list(A = 0.08, B = 0.12),
#'     treatment = list(A = 0.05, B = 0.08)
#'   ),
#'   d.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   d.hazard = list(
#'     control = list(A = 0.01, B = 0.01),
#'     treatment = list(A = 0.01, B = 0.01)
#'   ),
#'   seed = 123
#' )
#'
#' # Create analysis datasets
#' analysis_data <- analysisData(trial_data, E = c(50, 100, 150))
#'
#' # Generate comprehensive summary
#' summary_results <- testSummary(analysis_data, control = 1, hr_method = "Cox")
#'
#' # View results for first simulation, first analysis
#' print(summary_results[simID == 1 & analysis == 1])
#'
#' # Calculate power across simulations for overall population
#' power_analysis <- summary_results[subgroup == "Overall", .(
#'   power = mean(lr_pvalue < 0.05, na.rm = TRUE),
#'   mean_hr = mean(hazard_ratio, na.rm = TRUE),
#'   mean_events = mean(events_total, na.rm = TRUE)
#' ), by = analysis]
#' print(power_analysis)
#'
#' # Subgroup effect analysis
#' subgroup_effects <- summary_results[subgroup != "Overall", .(
#'   mean_hr = mean(hazard_ratio, na.rm = TRUE),
#'   median_hr = median(hazard_ratio, na.rm = TRUE)
#' ), by = .(analysis, subgroup)]
#' print(subgroup_effects)
#'
#' @seealso
#' \code{\link{analysisData}} for creating the input analysis datasets,
#' \code{\link{FastLRtest}} for log-rank test implementation,
#' \code{\link{FastHRest}} for hazard ratio estimation
#'
#' @import data.table
#' @export
testSummary <- function(data, control = 1, hr_method = "Cox") {
  # Input validation
  if (!is.data.table(data)) {
    data <- as.data.table(data)
  }

  required_cols <- c("simID", "analysis", "group", "tte", "event", "analysis.time")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  valid_methods <- c('PY', 'Pike', 'Peto', 'LR', 'Cox')
  if (!hr_method %in% valid_methods) {
    stop(paste("hr_method must be one of:", paste(valid_methods, collapse = ", ")))
  }

  # Check if subgroup column exists
  has_subgroups <- "subgroup" %in% names(data)

  # Set key for optimal performance
  if (has_subgroups) {
    setkeyv(data, c("simID", "analysis", "subgroup"))
  } else {
    setkeyv(data, c("simID", "analysis"))
  }

  # Pre-compute group indicators for efficiency
  data[, `:=`(
    is_control = as.integer(group == control),
    is_treatment = as.integer(group != control)
  )]

  # Helper function for log-rank test computation
  compute_lr_stats <- function(tte_vec, event_vec, group_vec) {
    if (length(unique(group_vec)) != 2 || sum(event_vec) < 2) {
      return(list(lr_statistic = NA_real_, lr_pvalue = NA_real_))
    }

    # Check if both groups have events
    events_by_group <- tapply(event_vec, group_vec, sum)
    if (any(events_by_group == 0)) {
      return(list(lr_statistic = NA_real_, lr_pvalue = NA_real_))
    }

    tryCatch({
      lr_stat <- FastLRtest(tte_vec, event_vec, group_vec, control, 2)
      list(
        lr_statistic = lr_stat,
        lr_pvalue = 1 - pchisq(lr_stat, 1)
      )
    }, error = function(e) {
      list(lr_statistic = NA_real_, lr_pvalue = NA_real_)
    })
  }

  # Helper function for hazard ratio computation
  compute_hr <- function(tte_vec, event_vec, group_vec) {
    if (length(unique(group_vec)) != 2) {
      return(NA_real_)
    }

    # Check if both groups have events
    events_by_group <- tapply(event_vec, group_vec, sum)
    if (any(events_by_group == 0)) {
      return(NA_real_)
    }

    tryCatch({
      hr_result <- FastHRest(tte_vec, event_vec, group_vec, control, hr_method)
      hr_result$HR
    }, error = function(e) {
      NA_real_
    })
  }

  # Overall population analysis using optimized data.table operations
  overall_results <- data[, {
    # Basic statistics computed in single pass
    list(
      subgroup = "Overall",
      analysis_time = analysis.time[1L],  # Use first value (should be identical)
      n_total = .N,
      n_control = sum(is_control),
      n_treatment = sum(is_treatment),
      events_total = sum(event),
      events_control = sum(event * is_control),
      events_treatment = sum(event * is_treatment),
      # Compute statistical tests
      lr_stats = list(compute_lr_stats(tte, event, group)),
      hazard_ratio = compute_hr(tte, event, group)
    )
  }, by = .(simID, analysis)]

  # Expand log-rank statistics
  overall_results[, `:=`(
    lr_statistic = sapply(lr_stats, function(x) x$lr_statistic),
    lr_pvalue = sapply(lr_stats, function(x) x$lr_pvalue)
  )]

  # Remove temporary column
  overall_results[, lr_stats := NULL]

  # Add hr_method column
  overall_results[, hr_method := hr_method]

  if (has_subgroups) {
    # Subgroup analysis using optimized data.table operations
    subgroup_results <- data[, {
      list(
        analysis_time = analysis.time[1L],
        n_total = .N,
        n_control = sum(is_control),
        n_treatment = sum(is_treatment),
        events_total = sum(event),
        events_control = sum(event * is_control),
        events_treatment = sum(event * is_treatment),
        hazard_ratio = compute_hr(tte, event, group),
        lr_statistic = NA_real_,  # No log-rank test for subgroups
        lr_pvalue = NA_real_      # No log-rank test for subgroups
      )
    }, by = .(simID, analysis, subgroup)]

    # Add hr_method column
    subgroup_results[, hr_method := hr_method]

    # Combine results efficiently
    final_results <- rbindlist(list(overall_results, subgroup_results),
                               use.names = TRUE, fill = TRUE)
  } else {
    final_results <- overall_results
  }

  # Remove temporary columns from original data
  data[, `:=`(is_control = NULL, is_treatment = NULL)]

  # Set optimal column order
  setcolorder(final_results, c("simID", "analysis", "subgroup", "analysis_time",
                               "lr_statistic", "lr_pvalue", "hazard_ratio", "hr_method",
                               "n_total", "n_control", "n_treatment",
                               "events_total", "events_control", "events_treatment"))

  # Sort results for consistency
  setorderv(final_results, c("simID", "analysis", "subgroup"))

  return(final_results)
}
