#' Comprehensive statistical analysis summary for clinical trial data
#'
#' This function performs comprehensive statistical analysis on clinical trial data
#' generated by \code{\link{analysisData}}. It calculates log-rank test statistics,
#' hazard ratios, patient counts, event counts, and analysis times for both overall
#' population and subgroups using data.table for maximum performance.
#'
#' @param data A data.table containing analysis data generated by \code{\link{analysisData}}.
#'   Must contain columns: simID, analysis, group, tte, event, analysis.time.
#'   May optionally contain subgroup column for subgroup analysis.
#' @param control A numeric value indicating which value in \code{group} represents
#'   the control group. Default is 1.
#' @param hr_method A character string specifying the hazard ratio estimation method.
#'   Must be one of "PY", "Pike", "Peto", "LR", or "Cox". Default is "Cox".
#'
#' @return A data.table containing comprehensive analysis results with the following columns:
#' \describe{
#'   \item{simID}{Simulation iteration ID}
#'   \item{analysis}{Analysis number}
#'   \item{subgroup}{Subgroup indicator ("Overall" for overall population, subgroup names for subgroups)}
#'   \item{analysis_time}{Analysis cutoff time (calendar time from study start)}
#'   \item{lr_statistic}{Log-rank test chi-square statistic (overall population only, NA for subgroups)}
#'   \item{lr_pvalue}{Log-rank test p-value (overall population only, NA for subgroups)}
#'   \item{hazard_ratio}{Estimated hazard ratio}
#'   \item{hr_method}{Method used for hazard ratio estimation}
#'   \item{n_total}{Total number of patients}
#'   \item{n_control}{Number of patients in control group}
#'   \item{n_treatment}{Number of patients in treatment group}
#'   \item{events_total}{Total number of events}
#'   \item{events_control}{Number of events in control group}
#'   \item{events_treatment}{Number of events in treatment group}
#' }
#'
#' @details
#' This function provides a comprehensive summary of clinical trial results by:
#'
#' \describe{
#'   \item{Log-rank Test}{
#'     Performs log-rank test using \code{\link{FastLRtest}} for the overall population
#'     at each analysis timepoint. Returns chi-square statistic and p-value.
#'   }
#'   \item{Hazard Ratio Estimation}{
#'     Calculates hazard ratios using \code{\link{FastHRest}} for both overall population
#'     and each subgroup using the specified method.
#'   }
#'   \item{Patient Counts}{
#'     Summarizes total patient numbers by group for overall population and subgroups.
#'   }
#'   \item{Event Counts}{
#'     Summarizes total event numbers by group for overall population and subgroups.
#'   }
#'   \item{Analysis Time}{
#'     Records the analysis cutoff time for each analysis.
#'   }
#' }
#'
#' All calculations are performed using data.table for maximum efficiency and are
#' stratified by simulation ID and analysis number.
#'
#' @examples
#' library(data.table)
#'
#' # Generate trial data with subgroups
#' trial_data <- simTrial(
#'   nsim = 50,
#'   N = list(
#'     control = c(A = 50, B = 50),
#'     treatment = c(A = 50, B = 50)
#'   ),
#'   a.time = list(
#'     control = list(A = c(0, 18), B = c(0, 18)),
#'     treatment = list(A = c(0, 18), B = c(0, 18))
#'   ),
#'   intensity = list(
#'     control = list(A = 50/18, B = 50/18),
#'     treatment = list(A = 50/18, B = 50/18)
#'   ),
#'   e.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   e.hazard = list(
#'     control = list(A = 0.08, B = 0.12),
#'     treatment = list(A = 0.05, B = 0.08)
#'   ),
#'   d.time = list(
#'     control = list(A = c(0, Inf), B = c(0, Inf)),
#'     treatment = list(A = c(0, Inf), B = c(0, Inf))
#'   ),
#'   d.hazard = list(
#'     control = list(A = 0.01, B = 0.01),
#'     treatment = list(A = 0.01, B = 0.01)
#'   ),
#'   seed = 123
#' )
#'
#' # Create analysis datasets
#' analysis_data <- analysisData(trial_data, E = c(50, 100, 150))
#'
#' # Generate comprehensive summary
#' summary_results <- testSummary(analysis_data, control = 1, hr_method = "Cox")
#'
#' # View results for first simulation, first analysis
#' print(summary_results[simID == 1 & analysis == 1])
#'
#' # Calculate power across simulations for overall population
#' power_analysis <- summary_results[subgroup == "Overall", .(
#'   power = mean(lr_pvalue < 0.05, na.rm = TRUE),
#'   mean_hr = mean(hazard_ratio, na.rm = TRUE),
#'   mean_events = mean(events_total, na.rm = TRUE)
#' ), by = analysis]
#' print(power_analysis)
#'
#' # Subgroup effect analysis
#' subgroup_effects <- summary_results[subgroup != "Overall", .(
#'   mean_hr = mean(hazard_ratio, na.rm = TRUE),
#'   median_hr = median(hazard_ratio, na.rm = TRUE)
#' ), by = .(analysis, subgroup)]
#' print(subgroup_effects)
#'
#' @seealso
#' \code{\link{analysisData}} for creating the input analysis datasets,
#' \code{\link{FastLRtest}} for log-rank test implementation,
#' \code{\link{FastHRest}} for hazard ratio estimation
#'
#' @import data.table
#' @export
testSummary <- function(data, control = 1, hr_method = "Cox") {
  # Input validation
  if (!is.data.table(data)) {
    data <- as.data.table(data)
  }

  required_cols <- c("simID", "analysis", "group", "tte", "event", "analysis.time")
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  valid_methods <- c('PY', 'Pike', 'Peto', 'LR', 'Cox')
  if (!hr_method %in% valid_methods) {
    stop(paste("hr_method must be one of:", paste(valid_methods, collapse = ", ")))
  }

  # Check if subgroup column exists
  has_subgroups <- "subgroup" %in% names(data)

  # Create overall population results
  overall_results <- data[, {
    # Analysis time (should be the same for all patients in same simID/analysis)
    analysis_time <- unique(analysis.time)[1]

    # Patient counts by group
    n_total <- .N
    n_control <- sum(group == control)
    n_treatment <- sum(group != control)

    # Event counts by group
    events_total <- sum(event)
    events_control <- sum(event[group == control])
    events_treatment <- sum(event[group != control])

    # Initialize results
    lr_statistic <- NA_real_
    lr_pvalue <- NA_real_
    hazard_ratio <- NA_real_

    # Log-rank test (only if sufficient events in both groups)
    if (events_control > 0 && events_treatment > 0 &&
        length(unique(group)) == 2) {
      tryCatch({
        lr_stat <- FastLRtest(tte, event, group, control, 2)
        lr_statistic <- lr_stat
        lr_pvalue <- 1 - pchisq(lr_stat, 1)
      }, error = function(e) {
        # Keep NA values if error occurs
      })
    }

    # Hazard ratio estimation (only if sufficient events in both groups)
    if (events_control > 0 && events_treatment > 0 &&
        length(unique(group)) == 2) {
      tryCatch({
        hr_result <- FastHRest(tte, event, group, control, hr_method)
        hazard_ratio <- hr_result$HR
      }, error = function(e) {
        # Keep NA values if error occurs
      })
    }

    list(
      subgroup = "Overall",
      analysis_time = analysis_time,
      lr_statistic = lr_statistic,
      lr_pvalue = lr_pvalue,
      hazard_ratio = hazard_ratio,
      hr_method = hr_method,
      n_total = n_total,
      n_control = n_control,
      n_treatment = n_treatment,
      events_total = events_total,
      events_control = events_control,
      events_treatment = events_treatment
    )
  }, by = .(simID, analysis)]

  # Create subgroup-specific results if subgroups exist
  if (has_subgroups) {
    subgroup_results <- data[, {
      # Analysis time (should be the same for all patients in same simID/analysis/subgroup)
      analysis_time <- unique(analysis.time)[1]

      # Patient counts by group
      n_total <- .N
      n_control <- sum(group == control)
      n_treatment <- sum(group != control)

      # Event counts by group
      events_total <- sum(event)
      events_control <- sum(event[group == control])
      events_treatment <- sum(event[group != control])

      # Initialize results
      hazard_ratio <- NA_real_

      # Hazard ratio estimation (only if sufficient events in both groups)
      if (events_control > 0 && events_treatment > 0 &&
          length(unique(group)) == 2) {
        tryCatch({
          hr_result <- FastHRest(tte, event, group, control, hr_method)
          hazard_ratio <- hr_result$HR
        }, error = function(e) {
          # Keep NA values if error occurs
        })
      }

      list(
        analysis_time = analysis_time,
        lr_statistic = NA_real_,  # Log-rank test only for overall population
        lr_pvalue = NA_real_,     # Log-rank test only for overall population
        hazard_ratio = hazard_ratio,
        hr_method = hr_method,
        n_total = n_total,
        n_control = n_control,
        n_treatment = n_treatment,
        events_total = events_total,
        events_control = events_control,
        events_treatment = events_treatment
      )
    }, by = .(simID, analysis, subgroup)]

    # Combine overall and subgroup results
    final_results <- rbindlist(list(overall_results, subgroup_results),
                               use.names = TRUE, fill = TRUE)
  } else {
    final_results <- overall_results
  }

  # Set column order for consistency
  if (has_subgroups) {
    col_order <- c("simID", "analysis", "subgroup", "analysis_time",
                   "lr_statistic", "lr_pvalue", "hazard_ratio", "hr_method",
                   "n_total", "n_control", "n_treatment",
                   "events_total", "events_control", "events_treatment")
  } else {
    col_order <- c("simID", "analysis", "subgroup", "analysis_time",
                   "lr_statistic", "lr_pvalue", "hazard_ratio", "hr_method",
                   "n_total", "n_control", "n_treatment",
                   "events_total", "events_control", "events_treatment")
  }

  setcolorder(final_results, col_order)

  # Sort by simID, analysis, and subgroup
  setorder(final_results, simID, analysis, subgroup)

  return(final_results)
}
